[project]
name = "universal-input-sanitizer"
version = "0.1.0"
description = "Sanitize and produce language-safe literals for input values"
authors = [{name="halrraiser", email="developer@rimurubot.xyz"}]
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
